---
- name: website setup on servers
  hosts: websrvgp
  become: yes
  remote_user: devops
  vars:
    tom_down_url: http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.43/bin/apache-tomcat-8.5.43.tar.gz
  tasks:
  - name: install open jdk on redhat
    yum: 
      name: java-1.6.0-openjdk.x86_64
      state: present
    when: ansible_distribution == "CentOS" 
  - name: intall open jdk on debian
    apt:
      name: java-1.6.0-openjdk.x86_64
      state: present
      update_cache: yes
    when: ansible_distribution == "ubuntu" 
  - name: download tomcat tar ball or binaries
    get_url:
      url: "{{tom_down_url}}"
      dest: /tmp/tomcat-8.tar.gz
  - name: add tomcat group
    group:
      name: tomcat   
      state: present
  - name: add tomcat user
    user:
      name: tomcat
      state: present
      shell: /bin/nologin
  - name: create directory tomcat
    file:
      path: /tmp/tomcat8      
      state: directory        
  - name: unarchinve tar ball 
    unarchive: 
      src: /tmp/tomcat-8.tar.gz
      dest: /tmp/tomcat8
      remote_src: yes
      list_files: yes
    register: unarchive_info
  - debug:
      msg: "{{unarchive_info.files[0].split('/')[0]}}"
  - name: Synchronize two directories on one remote host.
    synchronize:
      src: "/tmp/tomcat8/{{unarchive_info.files[0].split('/')[0]}}"
      dest: /usr/local/tomcat8/
    delegate_to: "{{ inventory_hostname }}"   
  - name: change ownership of /usr/local/tomcat
    file:
      path: /usr/local/tomcat
      owner: tomcat
      group: tomcat
      recurse: yes
  - name: setup tomcat svc file on centos 7
    template:
      src: templates/tomcat7-svcfile.j2      
      dest: /etc/systemd/system/tomcat.service
      mode: "a+x"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7.6'
  - name: deamon reload
    systemd:
      daemon_reload: yes 
    when: ansible_distribution_major_version > '6' or ansible_distribution_major_version '15' 
  - name: start and enable tomcat 
    service:
      name: tomcat   
      state: started
      enabled: yes   
