---
- hosts: websrvgp
  become: yes
  remote_user: devops
  tasks:
   - name: install httpd on centos
     yum:
      name: httpd
      state: present

   - name: enable httpd
     service:
      name: httpd
      state: started
      enabled: yes     

